[project]
name = "polars-for-data-science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.7",
    "polars>=1.33.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]
